extends: gritcode/server
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  camelcase: 0
  no-nested-ternary: 0
  no-sequences: 0
  no-return-assign: 0
  import/no-extraneous-dependencies: 0
