service: compare-userstats

package:
  individually: true
  exclude:
    - lib/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  credentials: ${file(credentials.yml):credentials}
  memorySize: 128
  timeout: 300
  cfLogs: true # < sls v1.10
  versionFunctions: false

functions:
  foo-add:
    handler: lib/foo/add.handler
    package:
      include: ['lib/foo/add/**']
    events:
      - http:
          path: /userstats
          method: POST
  swagger:
    handler: lib/swagger.handler
    package:
      include: ['lib/swagger/**']
    events:
      - http:
          path: /userstats/swagger
          method: GET
  preflight-foo-add:
    handler: lib/preflight.handler
    package:
      include: ['lib/preflight/**']
    events:
      - http:
          path: /userstats
          method: OPTIONS

plugins:
  - serverless-offline
