swagger: '2.0'
info:
  title: compare-userstats
  version: '1.0.0'
  description: API that persists daily stats of compare users usage

host: srv-compare.optizmo.<tld>
# NOTE: ignored by aws, custom basepath mapping needs to be setup in aws console
basePath: '/userstats'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  '/':
    post:
      summary: Create a foo
      description: |
          1. Authenticates request
          1. Validates request payload
          1. Creates new record in database
          1. Responds with the newly created record
      operationId: foo-add
      tags:
        - foo
      parameters:
        - $ref: "#/parameters/bearerToken"
        - $ref: "#/parameters/fooAdd"
        - $ref: "#/parameters/jsonContentType"
      responses:
        200:
          description: OK
        400:
          description: Invalid request
        401:
          description: Unauthorised
      x-amazon-apigateway-integration:
        type: aws_proxy
        passthroughBehavior: when_no_match
        uri: arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/<arn>/invocations
        httpMethod: POST
    options:
      operationId: preflight-foo-add
      parameters:
        - $ref: "#/parameters/bearerToken"
        - $ref: "#/parameters/fooAdd"
      description: Enable CORS by returning correct headers
      tags:
        - preflight
      responses:
        200:
          description: preflight headers
      x-amazon-apigateway-integration:
        type: aws_proxy
        passthroughBehavior: when_no_match
        uri: arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/<arn>/invocations
        httpMethod: POST


  '/swagger':
    get:
      description: swagger spec
      operationId: swagger
      tags:
        - swagger
      responses:
        200:
          description: swagger spec
      x-amazon-apigateway-integration:
        type: aws_proxy
        passthroughBehavior: when_no_match
        uri: arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/<arn>/invocations
        httpMethod: POST

definitions:
  FooAdd:
    type: object
    additionalProperties: false
    properties:
      bah:
        type: string
        example: 'Im a bah'
    required: [bah]

parameters:
  jsonContentType:
    name: content-type
    in: header
    description: request body mime type
    type: string
  bearerToken:
    name: authorization
    in: header
    description: authorization token
    required: true
    type: string
  fooAdd:
    in: body
    name: body
    description: Foo object to add
    required: true
    schema:
      $ref: '#/definitions/FooAdd'
